mindmap
  root((Human Dietary Protein Digestion))
    Stomach
      Chewing and swallowing
      Gastric acid activates pepsin
      Pepsin cleaves polypeptides
      Chyme enters duodenum
    Pancreas
      Trypsinogen to trypsin
      Chymotrypsin and elastase
      Carboxypeptidases
      Oligopeptides and free amino acids
    Brush Border
      Aminopeptidases
      DPP-IV peptidases
      PEPT1 dipeptide transport
      Sodium-dependent AA transporters
    Absorption
      Jejunum primary site
      Portal vein to liver
      Systemic aminoacidemia
    Protein Sources
      Whey fast 1 to 2 hours
      Casein slow 7 to 8 hours
      Plant variable matrix effects
